language: python
python:
  - '3.5'
env:
  matrix:
    - TOXENV=py35-django-18
    - TOXENV=py35-django-19
    - TOXENV=py35-django-110
    - TOXENV=py35-django-111
branches:
  only:
  - master
before_script:
  - pip freeze
install:
  - pip install tox
  - git clone https://github.com/Dmitri-Sintsov/djk-sample.git
  - cd djk-sample
script:
  - tox -e $TOXENV
