dist: trusty
sudo: required
addons:
  chrome: stable
language: python
python:
  - '3.5'
env:
  matrix:
    - TOXENV=py35-django-21-bs3
    - TOXENV=py35-django-21-bs4
    - TOXENV=py35-django-20-bs3
    - TOXENV=py35-django-20-bs4
    - TOXENV=py35-django-111-bs3
    - TOXENV=py35-django-111-bs4
branches:
  only:
  - master
before_script:
  - pip freeze
install:
  - PATH=$PATH:$HOME
  - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - google-chrome --version
  = echo $CHROME_DRIVER_VERSION
  - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - chmod 0755 ~/chromedriver
  - pip install tox
  - git clone https://github.com/Dmitri-Sintsov/djk-sample.git
  - cd djk-sample
script:
  - tox -e $TOXENV
