version: 2
defaults: &defaults
  docker:
  - image: circleci/python:latest-browsers
  environment:
    CHROME_BIN: "/usr/bin/google-chrome"
jobs:
  "bootstrap3":
    <<: *defaults
    steps:
      - checkout
      - run: |
          .circleci/env.sh
          (cd djk-sample && "$(pyenv root)/versions/3.6.8/bin/python3" -m tox -r -e py36-django-20-bs3)
  "bootstrap4":
    <<: *defaults
    steps:
      - checkout
      - run: |
          .circleci/env.sh
          (cd djk-sample && "$(pyenv root)/versions/3.6.8/bin/python3" -m tox -r -e py36-django-20-bs4)
workflows:
  version: 2
  all_steps:
    jobs:
      - "bootstrap3"
      - "bootstrap4"
