name: C/I Testing.

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, '3.10']
        django: [2.2, 3.2, '4.1']
        bootstrap: [3, 4, 5]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip wheel tox tox-pyenv setuptools pysqlite3 --user
    - name: Test with tox
      run: |
        echo Environment used to run the tests
        echo Kernel version
        uname -a
        echo System version
        lsb_release -a
        echo Python version
        python3 --version
        echo Chrome version
        google-chrome --version
        echo Chrome driver version
        chromedriver --version
        git clone https://github.com/Dmitri-Sintsov/djk-sample.git
        cd djk-sample
        python3 -m tox -r -e py${{ matrix.python }}-django-${{ matrix.django }}-bs${{ matrix.bootstrap }}
